on: [push, pull_request]
name: QA
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - uses: snok/install-poetry@v1
    - name: poetry install
      run: poetry install
    - name: pytest
      run: poetry run black --diff .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - uses: snok/install-poetry@v1
    - name: poetry install
      run: poetry install
    - name: pytest
      run: poetry run flake8 --ignore E501
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - uses: snok/install-poetry@v1
    - name: poetry install
      run: poetry install
    - name: pytest
      run: poetry run mypy --check-untyped-defs . --exclude ubuntu_lint/dput.py
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - uses: snok/install-poetry@v1
    - name: poetry install
      run: poetry install
    - name: pytest
      run: poetry run pytest --verbose
